POST http://localhost:5000/api/notes
Content-Type: application/json

{   
    "title": "Rencana Perjalanan",
    "text": "Mengunjungi Yogyakarta untuk riset lapangan",
    "pinned": false,
    "bookmarked": true,
    "createdAt": "2025-03-23T15:00:00Z"
}